# Generated by Django 5.2.8 on 2025-11-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saludos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('esta_publicado', models.BooleanField(default=True)),
            ],
        ),
    ]
